apiVersion: v1
kind: ServiceAccount
metadata:
  name: peerprep-collaboration-service
  namespace: peerprep
  annotations:
    iam.gke.io/gcp-service-account: peerprep-collaboration-service@peerprep-475911.iam.gserviceaccount.com
