apiVersion: v1
kind: ServiceAccount
metadata:
  name: history-service-sa
  namespace: peerprep
  annotations:
    iam.gke.io/gcp-service-account: history-service-sa@peerprep-475911.iam.gserviceaccount.com
