apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-service-sa
  namespace: peerprep
  annotations:
    iam.gke.io/gcp-service-account: peerprep-user-service@peerprep-475911.iam.gserviceaccount.com
