apiVersion: v1
kind: ConfigMap
metadata:
  name: history-service-config
  namespace: peerprep
data:
  # Server Configuration
  NODE_ENV: 'production'
  PORT: '8004'

  # Google Cloud Configuration
  GCP_PROJECT_ID: 'peerprep-475911'
  USE_SECRET_MANAGER: 'true'

  # Logging
  LOG_LEVEL: 'info'

  # CORS Configuration
  CORS_ORIGIN: 'http://34.8.234.19,https://34.8.234.19'
