apiVersion: v1
kind: ConfigMap
metadata:
  name: question-service-config
  namespace: peerprep
data:
  # Server Configuration
  NODE_ENV: 'production'
  PORT: '8001'

  # CORS Configuration
  ALLOWED_ORIGINS: 'http://34.8.234.19,https://34.8.234.19'

  # Redis Configuration
  REDIS_HOST: 'question-service-redis-service'
  REDIS_PORT: '6380'

  # GCP Configuration
  GCP_PROJECT_ID: 'peerprep-475911'
  USE_SECRET_MANAGER: 'true'
