apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: history-service-backend-config
  namespace: peerprep
spec:
  healthCheck:
    checkIntervalSec: 10
    port: 8004
    type: HTTP
    requestPath: /health
  timeoutSec: 30
  connectionDraining:
    drainingTimeoutSec: 60
  sessionAffinity:
    affinityType: 'NONE'
