apiVersion: v1
kind: Service
metadata:
  name: history-service
  namespace: peerprep
  labels:
    app: history-service
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"default": "history-service-backend-config"}'
spec:
  type: ClusterIP
  selector:
    app: history-service
  ports:
    - name: http
      port: 8004
      targetPort: 8004
      protocol: TCP
  sessionAffinity: None
